export const MUNICIPALITIES = [
  "Amsterdam",
  "Rotterdam",
  "Den Haag",
  "Utrecht",
  "Eindhoven",
  "Groningen",
  "Tilburg",
  "Almere",
  "Breda",
  "Nijmegen",
  "Arnhem",
  "Haarlem",
  "Enschede",
  "Apeldoorn",
  "Amersfoort",
  "Zaanstad",
  "Haarlemmermeer",
  "Zwolle",
  "Leiden",
  "Maastricht",
  "Dordrecht",
  "Ede",
  "Leeuwarden",
  "Zoetermeer",
  "Deventer",
  "Delft",
  "Alkmaar",
  "Heerlen",
  "Venlo",
  "Hilversum",
];

export const PROVINCES = [
  "Noord-Holland",
  "Zuid-Holland",
  "Utrecht",
  "Noord-Brabant",
  "Gelderland",
  "Overijssel",
  "Limburg",
  "Friesland",
  "Groningen",
  "Drenthe",
  "Flevoland",
  "Zeeland",
];

export const WATER_AUTHORITIES = [
  "Waterschap Rijn en IJssel",
  "Waterschap De Dommel",
  "Waterschap Rivierenland",
  "Waterschap Hollandse Delta",
  "Waterschap Amstel, Gooi en Vecht",
  "Waterschap Drents Overijsselse Delta",
  "Waterschap Hunze en Aa's",
  "Waterschap Scheldestromen",
  "Waterschap Zuiderzeeland",
  "Waterschap Vechtstromen",
  "Hoogheemraadschap van Delfland",
  "Hoogheemraadschap van Schieland en de Krimpenerwaard",
];

export const STATUSES = [
  "Vastgesteld",
  "In behandeling",
  "Ter inzage",
  "Voorlopig",
  "Vervallen",
  "Aangenomen",
  "Verworpen",
  "Aangehouden",
] as const;

export const PORTFOLIO_HOLDERS = [
  "Wethouder Wonen",
  "Wethouder Mobiliteit",
  "Wethouder Financiën",
  "Wethouder Ruimte",
  "Wethouder Zorg",
  "Wethouder Duurzaamheid",
  "Gedeputeerde Mobiliteit",
  "Gedeputeerde Economie",
  "Gedeputeerde Natuur",
  "Dagelijks Bestuur Waterschap",
  "Burgemeester",
  "Wethouder Openbare Orde",
  "Wethouder Sport & Cultuur",
] as const;

export const POLITICAL_PARTIES = [
  "VVD",
  "GroenLinks-PvdA",
  "BBB",
  "PVV",
  "D66",
  "CDA",
  "ChristenUnie",
  "SP",
  "DENK",
  "FvD",
  "PvdD",
  "SGP",
  "50PLUS",
  "BIJ1",
] as const;
