export type BoatPhoto = {
  id: string;
  src: string;
  alt: string;
  caption: string;
  span?: "wide" | "tall" | "normal";
};

/** Collagefotos voor /windkracht-vier/ — JPG in public/windkracht-vier/fotos/ */
export const BOAT_PHOTOS: BoatPhoto[] = [
  {
    id: "img_2218",
    src: "/windkracht-vier/fotos/IMG_2218.jpg",
    alt: "Windkracht Vier — Op het water",
    caption: "Op het water",
    span: "wide",
  },
  {
    id: "img_2215",
    src: "/windkracht-vier/fotos/IMG_2215.jpg",
    alt: "Windkracht Vier — Onder zeil",
    caption: "Onder zeil",
    span: "wide",
  },
  {
    id: "img_2216",
    src: "/windkracht-vier/fotos/IMG_2216.jpg",
    alt: "Windkracht Vier — Zeilen",
    caption: "Zeilen",
    span: "wide",
  },
  {
    id: "img_2217",
    src: "/windkracht-vier/fotos/IMG_2217.jpg",
    alt: "Windkracht Vier — Fok",
    caption: "Fok",
    span: "wide",
  },
  {
    id: "img_6058",
    src: "/windkracht-vier/fotos/IMG_6058.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6059",
    src: "/windkracht-vier/fotos/IMG_6059.jpg",
    alt: "Windkracht Vier — Profiel",
    caption: "Profiel",
  },
  {
    id: "img_6060",
    src: "/windkracht-vier/fotos/IMG_6060.jpg",
    alt: "Windkracht Vier — Op trailer",
    caption: "Op trailer",
  },
  {
    id: "img_6061",
    src: "/windkracht-vier/fotos/IMG_6061.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6062",
    src: "/windkracht-vier/fotos/IMG_6062.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6063",
    src: "/windkracht-vier/fotos/IMG_6063.jpg",
    alt: "Windkracht Vier — Mastvoet",
    caption: "Mastvoet",
  },
  {
    id: "img_6064",
    src: "/windkracht-vier/fotos/IMG_6064.jpg",
    alt: "Windkracht Vier — Dekbeslag",
    caption: "Dekbeslag",
  },
  {
    id: "img_6065",
    src: "/windkracht-vier/fotos/IMG_6065.jpg",
    alt: "Windkracht Vier — Tuigage",
    caption: "Tuigage",
  },
  {
    id: "img_6066",
    src: "/windkracht-vier/fotos/IMG_6066.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6067",
    src: "/windkracht-vier/fotos/IMG_6067.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6068",
    src: "/windkracht-vier/fotos/IMG_6068.jpg",
    alt: "Windkracht Vier — Houtwerk",
    caption: "Houtwerk",
    span: "tall",
  },
  {
    id: "img_6069",
    src: "/windkracht-vier/fotos/IMG_6069.jpg",
    alt: "Windkracht Vier — Kuip",
    caption: "Kuip",
  },
  {
    id: "img_6070",
    src: "/windkracht-vier/fotos/IMG_6070.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6071",
    src: "/windkracht-vier/fotos/IMG_6071.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6072",
    src: "/windkracht-vier/fotos/IMG_6072.jpg",
    alt: "Windkracht Vier — Rondhouten",
    caption: "Rondhouten",
    span: "tall",
  },
  {
    id: "img_6073",
    src: "/windkracht-vier/fotos/IMG_6073.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6074",
    src: "/windkracht-vier/fotos/IMG_6074.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6075",
    src: "/windkracht-vier/fotos/IMG_6075.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6076",
    src: "/windkracht-vier/fotos/IMG_6076.jpg",
    alt: "Windkracht Vier — Op de trailer",
    caption: "Op de trailer",
  },
  {
    id: "img_6077",
    src: "/windkracht-vier/fotos/IMG_6077.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6078",
    src: "/windkracht-vier/fotos/IMG_6078.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6079",
    src: "/windkracht-vier/fotos/IMG_6079.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6080",
    src: "/windkracht-vier/fotos/IMG_6080.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6081",
    src: "/windkracht-vier/fotos/IMG_6081.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6082",
    src: "/windkracht-vier/fotos/IMG_6082.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6083",
    src: "/windkracht-vier/fotos/IMG_6083.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6084",
    src: "/windkracht-vier/fotos/IMG_6084.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6085",
    src: "/windkracht-vier/fotos/IMG_6085.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6086",
    src: "/windkracht-vier/fotos/IMG_6086.jpg",
    alt: "Windkracht Vier — Scheepsnaam",
    caption: "Scheepsnaam",
  },
  {
    id: "img_6087",
    src: "/windkracht-vier/fotos/IMG_6087.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6088",
    src: "/windkracht-vier/fotos/IMG_6088.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6089",
    src: "/windkracht-vier/fotos/IMG_6089.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6090",
    src: "/windkracht-vier/fotos/IMG_6090.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6091",
    src: "/windkracht-vier/fotos/IMG_6091.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
    span: "tall",
  },
  {
    id: "img_6092",
    src: "/windkracht-vier/fotos/IMG_6092.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "img_6098",
    src: "/windkracht-vier/fotos/IMG_6098.jpg",
    alt: "Windkracht Vier — Aan de steiger",
    caption: "Aan de steiger",
  },
  {
    id: "img_6099",
    src: "/windkracht-vier/fotos/IMG_6099.jpg",
    alt: "Windkracht Vier — Ligplaats",
    caption: "Ligplaats",
  },
  {
    id: "img_6100",
    src: "/windkracht-vier/fotos/IMG_6100.jpg",
    alt: "Windkracht Vier — Jachthaven",
    caption: "Jachthaven",
  },
  {
    id: "img_6235",
    src: "/windkracht-vier/fotos/IMG_6235.jpg",
    alt: "Windkracht Vier — Op stalling",
    caption: "Op stalling",
  },
  {
    id: "img_6238",
    src: "/windkracht-vier/fotos/IMG_6238.jpg",
    alt: "Windkracht Vier — Windkracht Vier",
    caption: "Windkracht Vier",
  },
  {
    id: "foto_082965b4",
    src: "/windkracht-vier/fotos/foto-082965b4.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_5a1a20a7",
    src: "/windkracht-vier/fotos/foto-5a1a20a7.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_6a5aacbd",
    src: "/windkracht-vier/fotos/foto-6a5aacbd.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_6ca55993",
    src: "/windkracht-vier/fotos/foto-6ca55993.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_b128021b",
    src: "/windkracht-vier/fotos/foto-b128021b.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_b6e482b3",
    src: "/windkracht-vier/fotos/foto-b6e482b3.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_bcfb5046",
    src: "/windkracht-vier/fotos/foto-bcfb5046.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_c77081db",
    src: "/windkracht-vier/fotos/foto-c77081db.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_f3012fe9",
    src: "/windkracht-vier/fotos/foto-f3012fe9.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
  {
    id: "foto_fc874cbd",
    src: "/windkracht-vier/fotos/foto-fc874cbd.jpg",
    alt: "Windkracht Vier — Haven",
    caption: "Haven",
    span: "tall",
  },
];

export const HERO_PHOTO =
  BOAT_PHOTOS.find((p) => p.id === "img_2218") ?? BOAT_PHOTOS[0];
