import type { LegalAreaCategory } from "../types";

export interface LegalAreaDefinition {
  id: string;
  category: LegalAreaCategory;
  name: string;
  subAreas: string[];
  description?: string;
}

export const LEGAL_AREAS: LegalAreaDefinition[] = [
  {
    id: "civiel",
    category: "CIVIEL",
    name: "Civiel recht",
    description:
      "Civielrechtelijk onrechtmatig is niet hetzelfde als strafrechtelijk strafbaar.",
    subAreas: [
      "verbintenissenrecht",
      "onrechtmatige daad",
      "overeenkomstenrecht",
      "aansprakelijkheidsrecht",
      "schadevergoedingsrecht",
      "burenrecht",
      "goederenrecht",
      "huurrecht",
      "arbeidsrecht",
      "consumentenrecht",
      "ondernemingsrecht",
      "personen- en familierecht",
      "erfrecht",
      "privacyrechtelijke civiele vorderingen",
      "kort geding",
      "bodemprocedure",
      "verzoekschriftprocedure",
      "executie van civiele vonnissen",
      "dwangsommen",
      "contact-, straat- en gebiedsverboden",
      "rectificatie",
      "verbod en gebod",
      "verklaring voor recht",
    ],
  },
  {
    id: "straf",
    category: "STRAF",
    name: "Strafrecht",
    description:
      "Onderscheid: hinderlijk gedrag ≠ normoverschrijdend gedrag ≠ civielrechtelijk onrechtmatig ≠ bestuursrechtelijk handhaafbaar ≠ strafbaar.",
    subAreas: [
      "materieel strafrecht",
      "strafprocesrecht",
      "bedreiging",
      "belaging",
      "dwang",
      "mishandeling",
      "vernieling",
      "huisvredebreuk",
      "lokaalvredebreuk",
      "belediging",
      "smaad",
      "laster",
      "wederrechtelijke vrijheidsberoving",
      "afpersing",
      "afdreiging",
      "discriminatiedelicten",
      "seksuele misdrijven",
      "medeplegen",
      "medeplichtigheid",
      "poging",
      "uitlokking",
      "noodweer",
      "noodweerexces",
      "strafuitsluitingsgronden",
      "klachtmisdrijven",
      "bewijsminimum",
      "aangifte en klacht",
      "benadeelde partij",
      "schadevergoedingsmaatregel",
      "contact- en locatieverboden",
    ],
  },
  {
    id: "bestuur",
    category: "BESTUUR",
    name: "Bestuursrecht",
    subAreas: [
      "Algemene wet bestuursrecht",
      "besluiten",
      "beschikkingen",
      "bezwaar",
      "beroep",
      "hoger beroep",
      "voorlopige voorziening",
      "handhaving",
      "beginselplicht tot handhaving",
      "last onder dwangsom",
      "last onder bestuursdwang",
      "bestuurlijke boete",
      "evenredigheidsbeginsel",
      "zorgvuldigheidsbeginsel",
      "motiveringsbeginsel",
      "vertrouwensbeginsel",
      "gelijkheidsbeginsel",
      "misbruik van bevoegdheid",
      "openbaarheid van bestuur",
      "Woo",
      "gemeentelijke handhaving",
      "omgevingsrecht",
      "openbare orde",
      "woonoverlast",
      "APV",
      "gemeentelijke verordeningen",
      "privacy binnen bestuursorganen",
      "sociale zekerheid",
      "ambtenarenrecht",
      "economisch bestuursrecht",
    ],
  },
  {
    id: "constitutioneel",
    category: "CONSTITUTIONEEL",
    name: "Constitutioneel recht en mensenrechten",
    subAreas: [
      "Grondwet",
      "grondrechten",
      "directe werking van verdragsbepalingen",
      "artikelen 93 en 94 Grondwet",
      "EVRM",
      "EU-Grondrechtenhandvest",
      "proportionaliteit",
      "subsidiariteit",
      "positieve verplichtingen van de staat",
      "horizontale werking",
      "toegang tot de rechter",
      "eerlijk proces",
      "privacy",
      "vrijheid van meningsuiting",
      "eigendomsrecht",
      "non-discriminatie",
    ],
  },
  {
    id: "eu",
    category: "EU",
    name: "Europees Unierecht",
    subAreas: [
      "primaire EU-verdragen",
      "verordeningen",
      "richtlijnen",
      "besluiten",
      "aanbevelingen",
      "EU-Handvest",
      "rechtspraak Hof van Justitie",
      "rechtspraak Gerecht",
      "rechtstreekse werking",
      "conforme interpretatie",
      "voorrang van EU-recht",
      "staatsaansprakelijkheid",
      "prejudiciële procedures",
      "nationale implementatiewetgeving",
    ],
  },
  {
    id: "verdrag",
    category: "VERDRAG",
    name: "Europees verdragsrecht",
    subAreas: [
      "EVRM en protocollen",
      "rechtspraak EHRM",
      "Raad van Europa versus Europese Unie",
      "andere verdragen voor Nederland",
      "datum inwerkingtreding",
      "voorbehouden en verklaringen",
    ],
  },
  {
    id: "overig",
    category: "OVERIG",
    name: "Overige Nederlandse rechtsgebieden",
    subAreas: [
      "belastingrecht",
      "sociaalzekerheidsrecht",
      "vreemdelingenrecht",
      "jeugdrecht",
      "gezondheidsrecht",
      "tuchtrecht",
      "mededingingsrecht",
      "gegevensbeschermingsrecht",
      "intellectueel eigendomsrecht",
      "financieel recht",
      "insolventierecht",
      "aanbestedingsrecht",
    ],
  },
];

export const EXCEPTION_PHRASES = [
  "dit lijdt uitzondering indien",
  "behoudens bijzondere omstandigheden",
  "tenzij",
  "volgens vaste rechtspraak",
  "in beginsel",
  "onder omstandigheden",
  "alle omstandigheden van het geval",
  "anders dan de hoofdregel",
  "kan uitzondering worden aanvaard",
  "redelijkheid en billijkheid",
  "naar maatstaven van redelijkheid en billijkheid onaanvaardbaar",
  "zwaarwegende belangen",
  "bij hoge uitzondering",
];

export const SUCCESS_WEIGHTS: Record<string, number> = {
  juridischeGrondslag: 0.2,
  wettelijkeVereisten: 0.2,
  bewijskracht: 0.2,
  vergelijkbareJurisprudentie: 0.15,
  gezagJurisprudentie: 0.1,
  procedureleHaalbaarheid: 0.05,
  proportionaliteit: 0.05,
  verwachtVerweer: 0.05,
};

export const PROCESS_CHANCE_WARNING =
  "Dit is geen statistisch voorspelde zekerheid en geen garantie. " +
  "De indicatie is een gestructureerde juridische inschatting op basis van " +
  "de ingevoerde feiten, beschikbare bewijsstukken, toepasselijke rechtsregels " +
  "en gevonden vergelijkbare uitspraken. Een rechter kan anders oordelen.";
